<?php

use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;

/** @var \Magento\Framework\View\Element\Template $block */
$details = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);
$icon = $block->getData('icons')[$details['type']];
$id = $block->escapeHtml($block->getData('id'));
$expirationDate = explode("/", $details['expirationDate']);
$expMonth = $expirationDate[0] ?? '';
$expYear = $expirationDate[1] ?? '';
$publicHash = $block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH);
?>
<div data-mage-init='{
        "Forpsyte_SecurionPay/js/vault": {
            "container": "payment_<?= /* @noEscape */ $id ?>",
            "publicHash": "<?= $block->escapeHtml($publicHash) ?>",
            "ccNumber": "<?= $block->escapeHtml($details['maskedCC']) ?>",
            "ccType": "<?= $block->escapeHtml($details['type']) ?>",
            "ccExpMonth": "<?= $block->escapeHtml($expMonth) ?>",
            "ccExpYear": "<?= $block->escapeHtml($expYear) ?>",
            "code": "<?= $block->escapeHtml($block->getData('code')) ?>"
        }
    }' id="payment_<?= /* @noEscape */ $id ?>" class="admin__field">
    <div class="admin__field-control control">
        <input type="radio" id="token_switcher_<?= /* @noEscape */ $id ?>" name="payment[token_switcher]"/>
        <img src="<?= $block->escapeUrl($icon['url']) ?>"
             width="<?= $block->escapeHtmlAttr($icon['width']) ?>"
             height="<?= $block->escapeHtmlAttr($icon['height']) ?>"
             class="payment-icon" >
        <span><?= $block->escapeHtml(__('ending')) ?></span>
        <span><?= $block->escapeHtml($details['maskedCC']) ?></span>
        (<span><?= $block->escapeHtml(__('expires')) ?></span>:
        <span><?= $block->escapeHtml($details['expirationDate']) ?></span>)
    </div>
</div>

