<?php
/**
 * @var Simon\SecurionPay\Block\Adminhtml\Form\Cc $block
 */
$code = $block->escapeHtml($block->getMethodCode());
$orderTotal = $block->getQuote()->getGrandTotal();
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>" style="display:none">
    <p style="padding-left: 28px; padding-top: 10px">
        After you submit this order, you will be presented with an option to complete your payment.
    </p>
    <input type="hidden" id="<?= /* @noEscape */ $code ?>_charge_id"
           name="payment[chargeId]"/>
    <input type="hidden" id="<?= /* @noEscape */ $code ?>_customer_id"
           name="payment[customerId]"/>
    <input type="hidden" id="<?= /* @noEscape */ $code ?>_customer_id"
           name="payment[chargeAmount]" value="<?= /* @noEscape */ $orderTotal; ?>>"/>
</fieldset>

