<?php


/** @var Forpsyte\SecurionPay\Block\Payment $block */

$code = $block->escapeHtml($block->getCode());

?>
<script>
    //<![CDATA[
    require(
        [
            'Forpsyte_SecurionPay/js/securionpay',
            'jquery',
            'domReady!'
        ], function(SecurionPay, $) {
            let config = <?= /* @noEscape */ $block->getPaymentConfig() ?>,
                payment,
                form = $('#payment_form_<?= /* @noEscape */ $code ?>');

            config.active = form.length > 0 && !form.is(':hidden');
            payment = new SecurionPay(config);
        });
    //]]>
</script>
