<?php
/** @var \Simon\SecurionPay\Block\Adminhtml\Checkout\Payment $block */

$code = $block->escapeHtml($block->getCode());
?>
<script>
    //<![CDATA[
    require(
        [
            'Simon_SecurionPay/js/securionpay-checkout',
            'jquery',
            'domReady!'
        ], function(SecurionPayCheckout, $) {
            let config = <?= /* @noEscape */ $block->getPaymentConfig() ?>,
                payment,
                form = $('#payment_form_<?= /* @noEscape */ $code ?>');

            config.active = form.length > 0 && !form.is(':hidden');
            payment = new SecurionPayCheckout(config);
        });
    //]]>
</script>
